source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.6"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server
gem "puma", ">= 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# JSON API serialization
gem "jsonapi-serializer"

# Pagination
gem "kaminari"

# CORS support for React dev server
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
end

group :development do
  # gem "spring"
end

gem "simplecov", "~> 0.22.0", :group => :test
