import { z } from "zod";
// Auto-generated by Rails on boot from config/employee_options.yml.
// Never edit this import path — restart Rails to refresh.
import constants from "./constants.json";

// ── Derived typed arrays ────────────────────────────────────────────────
export const EMPLOYMENT_TYPES = constants.employment_types as Array<{
  value: string;
  label: string;
}>;

export const CURRENCIES = constants.currencies as [string, ...string[]];
export const JOB_TITLES = constants.job_titles as string[];
export const DEPARTMENTS = constants.departments as string[];
export const COUNTRIES   = constants.countries as string[];

/** Convenience map: "full_time" → "Full Time" */
export const EMPLOYMENT_TYPE_LABELS: Record<string, string> = Object.fromEntries(
  EMPLOYMENT_TYPES.map((e) => [e.value, e.label])
);

// ── Zod validation schema — mirrors backend rules ───────────────────────
const employmentTypeValues = EMPLOYMENT_TYPES.map((e) => e.value) as [
  string,
  ...string[]
];

export const employeeSchema = z.object({
  full_name:       z.string().min(1, "Full name is required").max(255, "Too long"),
  email:           z
                     .string()
                     .min(1, "Email is required")
                     .email("Must be a valid email address (e.g. jane@example.com)"),
  job_title:       z.string().min(1, "Please select a job title").max(255, "Too long"),
  department:      z.string().min(1, "Please select a department").max(255, "Too long"),
  country:         z.string().min(1, "Please select a country").max(255, "Too long"),
  salary:          z
                     .number({ message: "Salary must be a number" })
                     .gt(0, "Salary must be greater than 0")
                     .lt(10_000_000, "Salary must be less than 10,000,000"),
  currency:        z.enum(CURRENCIES, { message: "Please select a currency" }),
  employment_type: z.enum(employmentTypeValues, { message: "Please select an employment type" }),
  hired_on:        z.string().min(1, "Hire date is required"),
});

export type EmployeeFormValues = z.infer<typeof employeeSchema>;

// ── Formatting helpers ──────────────────────────────────────────────────
export function formatSalary(amount: number, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
